### ISSUE TITLE
bridge to DataWarrior

### ISSUE THREAD

**Issue by nbehrnd** [dkratzert/StructureFinder#3]
This is to suggest a bridge between your program, structurefinder, and Thomas Sanders'  DataWarrior.

[DataWarrior](http://openmolecules.org/datawarrior/features.html) is among the programs I use to compare small-molecule properties.  If their structure is expressed by a SMILES string, for example, the program allows to retrieve entries with sub-motifs in common.  It is possible to retrieve common scaffolds (e.g., Bemis-Murcko scaffolds), to compute _en bloc_ properties like clogP, and to display findings in various diagrams.

Since, beside SMILES strings, DataWarrior equally accepts `.sdf` files as input format retaining information about the atoms spatial arrangment, I would like to suggest structurefinder to provide with an export option of the .cif curated (or, a user-defined sub-set of .cif) as .sdf file which in turn could be used to work with DataWarrior.  Deriving from work with openbabel, maybe said concatenation could be extended from a pattern like

`babel *.mol2 test_output --unique`

I know that if *.mol2 were replaced by *.cif, much of the information regarding molecular connectivity is chopped into pieces and hence, lost.  However, DataWarrior already offers to complement searches in the [COD](http://www.crystallography.net/cod/index.php) on-line, or on-site ([hint in the manual](http://www.openmolecules.org/help/databases.html#COD)) to complement chemical computations in line with other data.  This suggested expansion of structurefinder' s scope _could_ offer to work with the structure data which aren't (yet) deposit in a data base (e.g., CCDC, ISCD, COD; pubmed)
[CCDC_generated_with_header.dwar.txt](https://github.com/dkratzert/StructureFinder/files/3956455/CCDC_generated_with_header.dwar.txt).

DataWarrior internally stores the data in its own, at least in portion non human-readable binary format.  As consequence, it isn't possible to get the .cif «as such» back from DataWarrior.  Still, I think the comparison of medchem data of «public» and «in house» structures could be attractive.

As an example file to showing just a little about DataWarrior's work, I requested the CCDC CSD API to compile a few entries SMILES strings along the structure codes.  DataWarrior assigned molecular formulae and total masses; all four properties stored in CCDC_generated_with_header.dwar.txt attached below (to work with DW, remove the .txt extension, as .dwar is the original file extension).

**Comment by dkratzert** [comment]
Im sorry, but I don't think I have the time for this...
