### ISSUE TITLE
struggling to update an already existing .sqlite file

### ISSUE THREAD

**Issue by nbehrnd** [dkratzert/StructureFinder#4]
**Is your feature request related to a problem? Please describe.**
From the CCDC teaching subset, I have three .cif files organized as the following:
>|
>|--folder_A: ADRENL.cif and BAPLOT01.cif
>|--folder_B: ACSALA01.cif

The situation:  on a Monday, I know only about the two structures deposit in folder_A. With "import directory" I'm able to create a database .sqlite file as A.sqlite and may move on.  On Wednesday, though, I become aware of ASCALA01.cif stored in a different folder_B which I would like to _add_ to the already existing database file.  After all, because the GUI of StructureFinder displays the path toward the .cif files, simultaneous differnt locations should not be problematic, I thought.

Reading the old database A.sqlite with "open database file" was not a problem.  Clicking on "Import directory" however erases all entries from StructureFinder's table and starts a new database.

**Describe the solution you'd like**
- I would like to add the .cif of a newly created directory into a .sqlite database which already manages old data, even if the directories do not share the same root.  For me, at present, already the simultaneous selection of two sub-folders within the same folder is impossible (test system: Linux Xubuntu 18.04.4 LTS).
- Considering StructureFinder as a tool to manage .cif data, I would like to read an existing .sqlite file _and then remove_ a particular cif, because, for example, the model of ADRENL.cif no longer is of interest and the file ADRENL.cif already was removed from the directory.

**Describe alternatives you've considered**
- Buidling a new .sqlite file _from scratch_ each time one of the .cif files enters / leaves a directory monitored by StructureFinder appears as a less efficient approach than updating only the changes, especially if done manually.

**Additional context**
StructureFinder run time application version 47 was deployed in Linux Xubuntu 18.04.4 LTS.

**Comment by dkratzert** [comment]
You can at least use the command line version at the moment. It just adds structures to an already existing database file.
I might add your request later.

**Comment by dkratzert** [comment]
Hi, I released a new version which has an "Append Directory" button in order to append new directories to the database.

"Considering StructureFinder as a tool to manage .cif data"
StructureFinder will never be a tool to manage cif data. It is for finding data only!
